name: Refactored workflow
on:
    workflow_dispatch:

jobs:
    build-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v7

            - name: build and push image to docker
              uses: ./build-test/

              with:
                DOCKERHUB_USERNAME: shreepalsingh
                DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN}}
                application_name: python-app

